name: CI

on:
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Prime cached fixtures
        run: |
          make data
          ls data/raw

      - name: Run lint (optional)
        run: |
          make lint
        continue-on-error: true

      - name: Run feature generation
        run: make features

      - name: Run pytest
        run: pytest

      - name: Cleanup artefacts
        run: make clean
